In [1]:
import numpy as np

In [124]:
import pandas as pd

In [13]:
i = np.random.random(3)
print(i)

[0.19811298 0.10358458 0.59958467]


In [14]:
i.max()

0.5995846730891268

In [24]:
data = np.array([1,2])
data_2 = np.ones(2)
print(data, data_2)

[1 2] [1. 1.]


In [30]:
print (data * 1.6)

[1.6 3.2]


In [32]:
data = np.array([1,2,3,4])
data

array([1, 2, 3, 4])

In [35]:
data[0]

1

In [36]:
data.sum()

10

In [37]:
data.mean()

2.5

In [38]:
data.prod()

24

In [40]:
data.std()

1.118033988749895

In [43]:
np.random.random((10,10))

array([[0.0878739 , 0.10261653, 0.15094933, 0.09974748, 0.83015653,
        0.45083269, 0.02801717, 0.14388816, 0.49956954, 0.61616853],
       [0.10601814, 0.51808803, 0.66610665, 0.12286755, 0.65597473,
        0.26939938, 0.84260725, 0.19256042, 0.63640879, 0.28079566],
       [0.05097292, 0.32871964, 0.55884022, 0.07663021, 0.6249195 ,
        0.73450212, 0.93736978, 0.87130302, 0.98254673, 0.97490793],
       [0.60003082, 0.56484488, 0.62554958, 0.08700037, 0.06405718,
        0.42389049, 0.01073803, 0.65586793, 0.10927115, 0.82793322],
       [0.23061439, 0.18660264, 0.63446842, 0.900539  , 0.91729922,
        0.56202531, 0.11265336, 0.79327937, 0.25293307, 0.18198854],
       [0.22466145, 0.82198632, 0.55257703, 0.19486352, 0.87686092,
        0.90229751, 0.16558969, 0.05984197, 0.25867115, 0.67138334],
       [0.47723707, 0.67484553, 0.76511775, 0.5481725 , 0.46428624,
        0.57730896, 0.99058956, 0.85017947, 0.70608643, 0.39447503],
       [0.27620784, 0.07140322, 0.6802541

In [73]:
ts = np.random.random((4,5,5)).round(2)//0.01
print(type(ts))
ts

<class 'numpy.ndarray'>


array([[[52., 97., 97., 65., 10.],
        [ 2., 40., 85., 72., 17.],
        [52., 56., 50., 32., 50.],
        [32., 14., 53., 61., 26.],
        [21., 79., 97., 67., 56.]],

       [[23., 43., 56., 61., 48.],
        [73.,  1., 81., 24.,  5.],
        [33., 62., 35., 53., 28.],
        [20., 93.,  5., 79., 47.],
        [98.,  2., 83., 70., 97.]],

       [[78., 10., 41., 21., 61.],
        [14., 46., 95., 88., 80.],
        [20., 21., 55., 40.,  5.],
        [56., 39., 64., 91., 23.],
        [65., 77., 28., 33., 20.]],

       [[ 7., 93., 87., 35., 10.],
        [40., 56., 17., 81., 72.],
        [62., 26., 81., 24., 33.],
        [32.,  8., 33., 20., 36.],
        [ 1., 65., 98., 28., 17.]]])

In [167]:
tss = np.random.randint(1, 100, size=(4,5,5))
print(type(tss))
tss

<class 'numpy.ndarray'>


array([[[43,  6, 84, 73, 96],
        [72, 83, 65, 22, 80],
        [41, 29, 18, 35, 63],
        [85, 35, 45, 34, 62],
        [16,  6, 58, 74, 76]],

       [[21, 27, 54, 35, 19],
        [25, 55, 38, 81, 17],
        [84, 74, 55,  7, 45],
        [51, 49, 14, 86, 53],
        [59, 52, 30, 76, 66]],

       [[93, 96, 89, 98, 39],
        [ 9, 22, 97, 38, 25],
        [ 4, 15, 55, 54, 29],
        [58, 95, 13, 20, 86],
        [70, 69, 53, 99, 11]],

       [[23, 71, 98, 88, 31],
        [61, 25, 99, 74, 16],
        [89, 48, 14, 21, 55],
        [88, 54, 17,  2, 34],
        [90, 65, 50, 14, 79]]])

In [68]:
ts.sum()

9.73967887571127

In [69]:
ts.prod()

2.63230719338754e-10

In [74]:
ty = np.array([[1,2],[3,4],[5,6]])
ty

array([[1, 2],
       [3, 4],
       [5, 6]])

In [195]:
ty.T

array([[1, 3, 5],
       [2, 4, 6]])

In [168]:
df = pd.read_csv('123.csv', sep=',')